# Generated by Django 5.2.9 on 2026-01-22 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="journalentry",
            old_name="user_id",
            new_name="user",
        ),
    ]
