# Generated by Django 5.2.9 on 2026-01-22 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfessionModal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("content", models.CharField(max_length=5000)),
                ("is_anonymous", models.BooleanField(default=True)),
                (
                    "topic",
                    models.CharField(
                        choices=[
                            ("STRESS", "Stress"),
                            ("ANXIETY", "Anxiety"),
                            ("DEPRESSION", "Depression"),
                            ("RELATIONSHIP", "Relationship Issues"),
                            ("OTHERS", "Others"),
                        ],
                        default="OTHERS",
                        max_length=50,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
