# Generated by Django 5.2.9 on 2026-01-22 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("confession", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="confessionmodal",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
