# Generated by Django 5.2.9 on 2026-03-28 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_userprofile_usergoal_userbadge"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="safety_plan",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='{"emergency_contacts":[{"name":"","phone":""}],"coping_strategies":[""]}',
            ),
        ),
    ]
